### ISSUE TITLE
UI-fix/resister.html

### ISSUE THREAD

**Issue by saezurucrow** [reiyiyi/SDVX-EXScoreTool#7]
`/resister`

**Comment by saezurucrow** [comment]
貼り付ける方式ではなく、CSVをファイル選択してもらうほうがUIとして楽かも？

**Comment by reiyiyi** [comment]
> 貼り付ける方式ではなく、CSVをファイル選択してもらうほうがUIとして楽かも？

ファイル選択する形式にした場合、スマートフォンからのスコア登録はどのように行えますかね…？

**Comment by saezurucrow** [comment]
たしかにスマホからの登録でファイル選択の操作は難しいですね。。(スマホでもCSVファイル保存はできると思われます)
PCだとファイル送信の方が楽だと思っているので、貼り付ける方法とファイル選択する方法と二つあるといいかもしれません。

**Comment by reiyiyi** [comment]
> たしかにスマホからの登録でファイル選択の操作は難しいですね。。(スマホでもCSVファイル保存はできると思われます)
> PCだとファイル送信の方が楽だと思っているので、貼り付ける方法とファイル選択する方法と二つあるといいかもしれません。

分かりました。ファイル送信方法も追加することも考えておきます🙇‍♂️

**Comment by saezurucrow** [comment]
今回の修正はUIの修正になるので、機能は追加しない方向でいきます

**Comment by saezurucrow** [comment]
resister → register?
