### ISSUE TITLE
UI-fix/setting

### ISSUE THREAD

**Issue by saezurucrow** [reiyiyi/SDVX-EXScoreTool#8]
- settings.index
- settings_error.index

**Comment by reiyiyi** [comment]
> - settings.index
> 
> - settings_error.index

現在のエラー表記ですが、settings_error.htmlファイルを削除し、JavaScript等を用いて実現させるという形に変えるべきかを考えております。てんあさんはどう考えますか？🙇‍♂️

**Comment by saezurucrow** [comment]
エラー内容にもよりますが、JSやテンプレートエンジンの処理で実現できそうです👍

**Comment by reiyiyi** [comment]
> エラー内容にもよりますが、JSやテンプレートエンジンの処理で実現できそうです👍

ありがとうございます！
今のところでは、入力できない文字が含まれていた場合や、文字数制限に引っかかる場合にエラーを表示するようにすることを考えております🙏

**Comment by saezurucrow** [comment]
了解です！理想はフロントとバックエンドで両方バリデーションを設定するほうが望ましいですね(JSはブラウザ上で簡単に解除できたりするので)

**Comment by reiyiyi** [comment]
> 了解です！理想はフロントとバックエンドで両方バリデーションを設定するほうが望ましいですね(JSはブラウザ上で簡単に解除できたりするので)

分かりました。ではその方針で行きましょう🙇‍♂️

**Comment by saezurucrow** [comment]
error表示は別PRで対応するため、一旦レイアウト変更のみ対応いたします
